USE CityTour

go

INSERT INTO Product
            (ImageUrl,
             Summary,
             Latitude,
             Longitude,
             CategoryId,
             Price,
             Marker,
             NAME)
VALUES      ('Images/church1.jpg',
             'The Church is an active parish that offers English-language Masses both weekly and several times on Sunday. If you are interested in attending Mass in English then this is your best bet in Paris (and probably the only one).',
             48.857416,
             2.356063,
             1,
             39.99,
             'scripts/markers/church.png',
             'St. Josephs'),
            ('Images/church2.jpg',
             'In 1870 war broke out between France and Germany. The Council that was being held in the Vatican at the time was suspended and the Pope, no longer under the protection of French troops, considered himself a prisoner within the Vatican.',
             48.857318,
             2.357179,
             1,
             29.99,
             'scripts/markers/church.png',
             'Sacré-Cœur'),
            ('Images/church3.jpg',
             'The current church of Saint-Sulpice took the place of a small shrine dedicated to Saint-Sulpice-des-Champs, which dates back to the twelfth century. Rebuilt and expanded in the fourteenth and sixteenth centuries, it eventually be insufficient for the population of the parish (with huge, it was said, a hundred thousand people) which came to settle convents and buildings.',
             48.859661,
             2.355570,
             1,
             19.99,
             'scripts/markers/church.png',
             'Saint-Sulpice'),
            ('Images/church4.jpg',
             'The American Church in Paris (ACP) welcomes you to worship each Sunday at one of our three services. The 09h00 service is a weekly communion service; the 11h00 service is a traditional service with special music from one of our guest soloists or various choirs; the 13h30 service is a contemporary service.',
             48.859746,
             2.354110,
             1,
             49.99,
             'scripts/markers/church.png',
             'Église américaine'),
            ('Images/church5.jpg',
             'On a long walk though the area, we approached the church from the back and realized it was one we had never before visited. We entered and spotted a handful of sisters in their grey and white habits as well as a number of worshippers on their knees with their foreheads to the stone floor, praying. As we walked quietly',
             48.859986,
             2.355934,
             1,
             49.99,
             'scripts/markers/church.png',
             'Saint-Gervais'),
            ('Images/museum1.jpg',
             'The national museum of the Musée dOrsay opened to the public on 9 December 1986 to show the great diversity of artistic creation in the western world between 1848 and 1914. It was formed with the national collections coming mainly from three establishments.',
             48.860861,
             2.350270,
             2,
             29.99,
             'scripts/markers/building.png',
             'Musée dOrsay'),
            ('Images/museum2.jpg',
             'In 1969, President Georges Pompidou decided that the vacant site of the Plateau Beaubourg should be used for the construction of a multidisciplinary cultural centre of an entirely new type.',
             48.861157,
             2.348231,
             2,
             29.99,
             'scripts/markers/building.png',
             'Centre Pompidou'),
            ('Images/museum3.jpg',
             'With about 10 000 works, The City of Paris Museum of modern art museum collections represent the wealth of the artistic creation in XXth and XXIth centuries and testifies of the dynamism of the contemporary artistic scene.',
             48.861313,
             2.346793,
             2,
             39.99,
             'scripts/markers/building.png',
             'Modern Art'),
            ('Images/museum4.jpg',
             'Behind this somewhat mysterious name is hidden one of the capital’s most genuinely Parisian museums. The oldest of the municipal museums tells the story of Paris from a bygone era (a prehistoric dugout canoe dating from 4600 BC) to the present day, in all its immense variety.',
             48.860776,
             2.343339,
             2,
             9.99,
             'scripts/markers/building.png',
             'Musée Carnavalet'),
            ('Images/museum5.jpg',
             'The Musée Rodin and Akim Monet present several iconic bronze sculptures in correspondence with carefully selected works by Louise Bourgeois, George Grosz, Henri Matisse and a figure from classical antiquity.',
             48.860452,
             2.343832,
             2,
             19.99,
             'scripts/markers/building.png',
             'Musée Rodin'),
            ('Images/museum6.jpg',
             'One year later, the RMN-Grand Palais partnered with the Musée national Picasso-Paris to open a new Library and Gift Shop outside the museum walls. A different kind of space, designed with the help of the architectural firm Jean-François Bodin, recalls the life of Picasso in his studio, a studio that is both past and present.',
             48.859732,
             2.343467,
             2,
             29.99,
             'scripts/markers/building.png',
             'Musée Picasso'),
            ('Images/building1.jpg',
             'Of all the Grands Projets in Paris, none created such a stir as the Pei Pyramids in the courtyard of the famous Louvre Museum. Spectacular in concept and form, they provide a startling reminder of the audacious ability of modern architects to invigorate and re-circulate traditional architectural forms...',
             48.859449,
             2.342373,
             3,
             119.99,
             'scripts/markers/ferris.png',
             'Pyramide'),
            ('Images/building2.jpg',
             'The Grande Armee had conquered most of Europe and was then considered invicible. After his Austerlitz victory in 1805, Napoleon said to his soldiers : You will return home through archs of triumph',
             48.858659,
             2.343553,
             3,
             69.99,
             'scripts/markers/ferris.png',
             'Arc Triomphe'),
            ('Images/building3.jpg',
             'The Eiffel Tower is a wrought iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.',
             48.858715,
             2.345206,
             3,
             39.99,
             'scripts/markers/ferris.png',
             'Eiffel Tower'),
            ('Images/building4.jpg',
             'The Luxembourg Palace is located at 15 rue de Vaugirard in the 6th arrondissement of Paris. It was originally built to the designs of the French architect Salomon',
             48.858489,
             2.346793,
             3,
             79.99,
             'scripts/markers/ferris.png',
             'Luxembourg'),
            ('Images/building5.jpg',
             'The Sainte-Chapelle is a royal chapel in the Gothic style, within the medieval Palais de la Cité, the residence of the Kings of France until the 14h century, on the Île de la Cité in the heart of Paris',
             48.858052,
             2.349755,
             3,
             29.99,
             'scripts/markers/ferris.png',
             'Sainte-Chapelle'),
            ('Images/building6.jpg',
             'Italian-style opera house with ceiling painted by Chagall & library museum in 19th-century building.',
             48.858221,
             2.352716,
             3,
             29.99,
             'scripts/markers/ferris.png',
             'Opéra National') 
