BEGIN TRY
	BEGIN TRANSACTION
		IF COL_LENGTH('User', 'role') IS NOT NULL
	BEGIN
		ALTER TABLE dbo.[User]
		Drop CONSTRAINT DF__User__role__73852659

		ALTER TABLE dbo.[User]
		DROP COLUMN role
	END
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION 
	RAISERROR('Could not alter tables', 16,1)
END CATCH


